#!/bin/bash

java $JAVA_OPTS \
    -DPROVIDER_AVCURRENCY_URL="$PROVIDER_AVCURRENCY_URL" \
    -DPROVIDER_AVEXCHANGERATE_URL="$PROVIDER_AVEXCHANGERATE_URL" \
    -DPROVIDER_AVHISTORIC_URL="$PROVIDER_AVHISTORIC_URL" \
    -DPROVIDER_V6EXCHANGERATE_URL="$PROVIDER_V6EXCHANGERATE_URL" \
    -DREDIS_PORT="$REDIS_PORT" \
    -DREDIS_PASSWORD="$REDIS_PASSWORD" \
    org.springframework.boot.loader.JarLauncher