provider:
  AVCurrency:
    url: ${PROVIDER_AVCURRENCY_URL}
  AVExchangeRate:
    url: ${PROVIDER_AVEXCHANGERATE_URL}
  AVHistoricExchangeRateProvider:
    url: ${PROVIDER_AVHISTORIC_URL}
  V6ExchangeRate:
    url: ${PROVIDER_V6EXCHANGERATE_URL}

# redis
spring:
  redis:
    host: redis01
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    ssl: false
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 30000