server:
  port: ${APP_PORT}

provider:
  AVCurrency:
    url: ${PROVIDER_AVCURRENCY_URL}
  AVExchangeRate:
    url: ${PROVIDER_AVEXCHANGERATE_URL}
  AVHistoricExchangeRateProvider:
    url: ${PROVIDER_AVHISTORIC_URL}
  V6ExchangeRate:
    url: ${PROVIDER_V6EXCHANGERATE_URL}