version: '3.7'

services:

  elasticsearch01-exchange-rate:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - elasticsearch01:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
    ports:
      - ${ES_PORT}:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://elasticsearch01-exchange-rate:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - elk

  setup:
    depends_on:
      elasticsearch01-exchange-rate:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    user: "0"
    command: >
      bash -c '
        echo "Waiting for Elasticsearch availability";
        until curl -s http://elasticsearch01-exchange-rate:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST -u "elastic:${ELASTICSEARCH_PASSWORD}" -H "Content-Type: application/json" http://elasticsearch01-exchange-rate:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_SYSTEM_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    networks:
      - elk

  logstash-exchange-rate:
    depends_on:
      elasticsearch01-exchange-rate:
        condition: service_healthy
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5045:5045
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    networks:
      - elk

  kibana-exchange-rate:
    depends_on:
      elasticsearch01-exchange-rate:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    ports:
      - ${KIBANA_PORT}:5601
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
      ELASTICSEARCH_HOSTS: http://elasticsearch01-exchange-rate:9200
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch01: